name: Docker Image CI

on:
  push:
    branches: [ "release/2.6" ]
  pull_request:
    branches: [ "release/2.6" ]

jobs:

  build:

    runs-on: ubuntu-latest

    

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        # root-reserve-mb: 5120
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - uses: actions/checkout@v3
    - name: Build
      run: |
        echo "Free space:"
        df -h

    - name: 登录腾讯云  docker 仓库
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REPO_HOST }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: 构建和推送到 docker 仓库
      uses: docker/build-push-action@v4
      with:
        context: ./deploy/docker/hubserving/kie/gpu/
        push: true
        tags: ${{ secrets.DOCKER_REPO_HOST }}/ppocr:latest
